# Generated by Django 3.0 on 2024-07-26 15:50

from django.db import migrations, connection


def delete_old_tables(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS profile_profile;")
        cursor.execute("DROP TABLE IF EXISTS address_address;")
        cursor.execute("DROP TABLE IF EXISTS letting_letting;")

class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_delete_profile'),
    ]

    operations = [
        migrations.RunPython(delete_old_tables),
    ]
